import type { Asset, Sale, Seller } from "@/lib/types"

// Mock sellers
export const mockSellers: Seller[] = [
  {
    id: "seller_1",
    username: "RobloxDev",
    avatar: "/placeholder.svg?height=200&width=200",
    discordId: "123456789",
    badges: ["مطور محترف", "بائع موثوق"],
    joinDate: "2023-01-15",
    totalSales: 48,
    listedAssets: 12,
    averageRating: 4.8,
  },
  {
    id: "seller_2",
    username: "GameCreator",
    avatar: "/placeholder.svg?height=200&width=200",
    discordId: "987654321",
    badges: ["بائع جديد"],
    joinDate: "2023-05-20",
    totalSales: 7,
    listedAssets: 5,
    averageRating: 4.2,
  },
  {
    id: "seller_3",
    username: "MapDesigner",
    avatar: "/placeholder.svg?height=200&width=200",
    discordId: "456789123",
    badges: ["مصمم مابات", "بائع مميز"],
    joinDate: "2022-11-10",
    totalSales: 32,
    listedAssets: 8,
    averageRating: 4.6,
  },
]

// Mock assets
export const mockAssets: Asset[] = [
  {
    id: "asset_1",
    title: "ماب حرب الوقت",
    description: "ماب مدينة كاملة مع مباني ومناطق متنوعة، مثالية لألعاب المحاكاة والمغامرات.",
    price: 2500,
    category: "maps",
    images: [
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
    ],
    rating: 4.7,
    ratingCount: 23,
    seller: mockSellers[0],
    createdAt: "2023-08-15T10:30:00Z",
  },
  {
    id: "asset_2",
    title: "نظام اقتصادي متكامل",
    description: "نظام اقتصادي كامل مع عملات، متاجر، وإمكانية الشراء والبيع بين اللاعبين.",
    price: 3500,
    category: "systems",
    images: ["/placeholder.svg?height=720&width=1280", "/placeholder.svg?height=720&width=1280"],
    rating: 4.9,
    ratingCount: 17,
    seller: mockSellers[0],
    createdAt: "2023-09-05T14:20:00Z",
  },
  {
    id: "asset_3",
    title: "لعبة مغامرات كاملة",
    description: "لعبة مغامرات كاملة مع مراحل متعددة، أعداء، ونظام تقدم. جاهزة للنشر مباشرة.",
    price: 5000,
    category: "games",
    images: [
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
    ],
    rating: 4.5,
    ratingCount: 12,
    seller: mockSellers[2],
    createdAt: "2023-07-22T09:15:00Z",
  },
  {
    id: "asset_4",
    title: "نظام تخصيص الشخصيات",
    description: "نظام متقدم لتخصيص الشخصيات مع مئات الخيارات والإكسسوارات.",
    price: 1800,
    category: "systems",
    images: ["/placeholder.svg?height=720&width=1280", "/placeholder.svg?height=720&width=1280"],
    rating: 4.3,
    ratingCount: 9,
    seller: mockSellers[1],
    createdAt: "2023-10-10T16:45:00Z",
  },
  {
    id: "asset_5",
    title: "ماب جزيرة استوائية",
    description: "ماب جزيرة استوائية مفصلة مع شواطئ، غابات، وكهوف. مثالية لألعاب البقاء.",
    price: 2200,
    category: "maps",
    images: ["/placeholder.svg?height=720&width=1280", "/placeholder.svg?height=720&width=1280"],
    rating: 4.6,
    ratingCount: 14,
    seller: mockSellers[2],
    createdAt: "2023-08-30T11:20:00Z",
  },
  {
    id: "asset_6",
    title: "نظام معارك متقدم",
    description: "نظام معارك متقدم مع أسلحة متنوعة، تأثيرات خاصة، ونظام تقدم.",
    price: 2800,
    category: "systems",
    images: ["/placeholder.svg?height=720&width=1280", "/placeholder.svg?height=720&width=1280"],
    rating: 4.8,
    ratingCount: 21,
    seller: mockSellers[0],
    createdAt: "2023-09-18T13:10:00Z",
  },
  {
    id: "asset_7",
    title: "لعبة محاكاة مطعم",
    description: "لعبة محاكاة مطعم كاملة مع نظام طهي، خدمة زبائن، وإدارة مالية.",
    price: 4200,
    category: "games",
    images: [
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
      "/placeholder.svg?height=720&width=1280",
    ],
    rating: 4.4,
    ratingCount: 11,
    seller: mockSellers[1],
    createdAt: "2023-10-05T10:30:00Z",
  },
  {
    id: "asset_8",
    title: "مجموعة أصوات وموسيقى",
    description: "مجموعة كاملة من الأصوات والموسيقى لألعاب متنوعة. أكثر من 100 ملف صوتي.",
    price: 1500,
    category: "other",
    images: ["/placeholder.svg?height=720&width=1280"],
    rating: 4.2,
    ratingCount: 8,
    seller: mockSellers[2],
    createdAt: "2023-10-15T15:40:00Z",
  },
]

// Mock sales
export const mockSales: Sale[] = [
  {
    id: "sale_1",
    asset: {
      id: "asset_1",
      title: "خريطة مدينة متكاملة",
      category: "maps",
      image: "/placeholder.svg?height=720&width=1280",
    },
    buyer: {
      id: "buyer_1",
      username: "GameMaster",
      avatar: "/placeholder.svg?height=200&width=200",
    },
    price: 2500,
    date: "2023-10-18T14:30:00Z",
  },
  {
    id: "sale_2",
    asset: {
      id: "asset_3",
      title: "لعبة مغامرات كاملة",
      category: "games",
      image: "/placeholder.svg?height=720&width=1280",
    },
    buyer: {
      id: "buyer_2",
      username: "RobloxFan",
      avatar: "/placeholder.svg?height=200&width=200",
    },
    price: 5000,
    date: "2023-10-17T09:15:00Z",
  },
  {
    id: "sale_3",
    asset: {
      id: "asset_6",
      title: "نظام معارك متقدم",
      category: "systems",
      image: "/placeholder.svg?height=720&width=1280",
    },
    buyer: {
      id: "buyer_3",
      username: "DevBuilder",
      avatar: "/placeholder.svg?height=200&width=200",
    },
    price: 2800,
    date: "2023-10-16T16:45:00Z",
  },
  {
    id: "sale_4",
    asset: {
      id: "asset_2",
      title: "نظام اقتصادي متكامل",
      category: "systems",
      image: "/placeholder.svg?height=720&width=1280",
    },
    buyer: {
      id: "buyer_4",
      username: "CreativeGamer",
      avatar: "/placeholder.svg?height=200&width=200",
    },
    price: 3500,
    date: "2023-10-15T11:20:00Z",
  },
]
